package Java_Concepts.Multithreading.A1Thread.ThreadMethods;

public class ThreadYeild extends Thread{
    private ThreadYeild(String name){
        super(name);
    }

    @Override
    public void run(){
        for(int i=0;i<5;i++){
            System.out.println(Thread.currentThread().getName()+" is Running......");
            Thread.yield(); // running thread equaly
        }
        try{
            Thread.sleep(10);
        }catch(Exception e){
            System.out.print(e);
        }
    }

    public static void main(String[] args){
        ThreadYeild t1 = new ThreadYeild("t1");
        ThreadYeild t2 = new ThreadYeild("t2");
        t1.start();
        t2.start();
    }
}

// without yeild method only one thread is running continusly
//t2 is Running......
//t2 is Running......
//t2 is Running......
//t2 is Running......
//t2 is Running......
//t1 is Running......
//t1 is Running......
//t1 is Running......
//t1 is Running......
//t1 is Running......

// with yeild method
//t1 is Running......
//t2 is Running......
//t1 is Running......
//t2 is Running......
//t1 is Running......
//t2 is Running......
//t1 is Running......
//t2 is Running......
//t1 is Running......
//t2 is Running......